apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-myeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-myeb
    app.kubernetes.io/part-of: test-app-zsdw
  name: docker-devfile-sample-hello-world-myeb
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-myeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-myeb
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/build-e2e-qbwr-tenant/test-app-zsdw/docker-devfile-sample-hello-world-myeb@sha256:8b4c97b75aab70a571968dd6a804d80c22207c77b8eafcc9338a47aca1373630
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
